### ISSUE TITLE
I get an error when I create a new event type on the fly

### ISSUE THREAD

**Issue by combinatorist** [egeehartz/gatherings-app#40]
I can share more info if you're interested.

**Comment by egeehartz** [comment]
Yes, I'm very curious! I realized after re-reading some of the code that anyone using this HAS to have eventType "other" with an id of 6. So I'm guessing this also has to do with that?

**Comment by combinatorist** [comment]
Yeah - I bet it's related. I started with the empty database from the
Readme and tried to create an event type "party", but there were no events
types in the database when I checked later, just an 'eventTypeId' of 1 I
think.
